version: "3.1"

services:
  db:
    container_name: db.coletsgo.local
    image: postgres:latest
    restart: always
    ports:
      - "${PGPORT}:5432"
    environment:
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
